apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
images:
- digest: sha256:9e7f26fd60336aefc888a9ae8ee6a7c246ca7279385d08416b2d286af268acbf
  name: quay.io/monishkumar/project-demo
  newName: quay.io/monishkumar/project-demo:df2387efe29cb49ffdaaec20ed751a66e1c5c8f6
