apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
images:
- digest: sha256:f6c1d5341ea2a52cc7a969c240731e49507fd0e8c6e077170827a02040dcd410
  name: quay.io/monishkumar/project-demo
  newName: quay.io/monishkumar/project-demo:b4975c669e555618d5296521c122b0f3cb28415c
