apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
images:
- digest: sha256:64e1476d976a7858abf60e238bc9c7a01a4ac268341e6fdc4dce01def958689f
  name: quay.io/monishkumar/project-demo
  newName: quay.io/monishkumar/project-demo:df2387efe29cb49ffdaaec20ed751a66e1c5c8f6
