apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
images:
- digest: sha256:3ea32949712b194776c7d903229cd2cc2216938563247a8e753a6f843a75f4f7
  name: quay.io/monishkumar/project-demo
  newName: quay.io/monishkumar/project-demo:df2387efe29cb49ffdaaec20ed751a66e1c5c8f6
