apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
images:
- digest: sha256:026fdefeb98e66da761d28c2ebf8c539a80d559cc285fac1550e0728cf649480
  name: quay.io/monishkumar/project-demo
  newName: quay.io/monishkumar/project-demo:d2684e5339303c02a83e76f45cee84d888a9feb5
